### ISSUE TITLE
Payment processors?

### ISSUE THREAD

**Issue by AlexCline** [switowski/deploystack#10]
Would be interesting to see options available for sites to accept payments. Paypal, stripe, etc? I'm not familiar with all offerings, including smaller ones, but it would be useful to have listed.

**Comment by switowski** [comment]
Thanks for the suggestion, indeed it looks interesting as a slightly more advanced topic to discuss. I will keep it in mind!

**Comment by switowski** [comment]
Closing, this project will no longer be updated.
