### ISSUE TITLE
NameSilo for domains

### ISSUE THREAD

**Issue by chauffer** [switowski/deploystack#12]
http://namesilo.com

**Comment by switowski** [comment]
Thanks, didn't know them! They look nice and developers seems to recommend them (https://www.reddit.com/r/webdev/comments/52458g/can_i_trust_namesilocom/). Any personal experience with that company ?

**Comment by chauffer** [comment]
Yep, I have all my domains I care about with them; never had any issues and when I needed to contact support for some transfers they were pretty helpful.
