### ISSUE TITLE
Pingdom for monitoring

### ISSUE THREAD

**Issue by chauffer** [switowski/deploystack#13]
http://pingdom.com

**Comment by switowski** [comment]
Pingdom doesn't have any free plans (which makes it less appealing than other recommended companies - Uptime Robot and StatusCake). But they have a nice set of tools apart from the uptime monitoring, so I will keep an eye on them and maybe I can squeeze them somewhere during the next updates :)
Thanks for the suggestion!

**Comment by switowski** [comment]
Closing, this project will no longer be updated.
