### ISSUE TITLE
Display IPv6 Support in Hosting selection

### ISSUE THREAD

**Issue by andir** [switowski/deploystack#15]
Since the future of the internet is IPv6 you should probably display if a hosting company does offer IPv6 services.

**Comment by switowski** [comment]
Great idea, thanks!
Please, correct me if I'm wrong, but quick googling tells me that DigitalOcean, Linode and AWS offer IPv6, so only Heroku doesn't offer it (at least I couldn't find any mention of that)?

**Comment by andir** [comment]
As afar as I know AWS does only offer IPv6 if you go to some kind of
private cloud within their offerings. The general public offer does not
provide it as far as I'm informed.
