### ISSUE TITLE
Sentry for error tracking

### ISSUE THREAD

**Issue by ehfeng** [switowski/deploystack#17]
Hi, I'm Eric from the [hacker news thread](https://news.ycombinator.com/item?id=13695062). Would love to add Sentry to this list. Let me know if you'd prefer I just open a PR for this.

**Comment by switowski** [comment]
Hey, thanks for the suggestion (many people suggested Sentry and it was a huge oversight on my side, that I didn't add it since the beginning), but the latest commit (539665fabc1) is fixing this issue :smile:
