### ISSUE TITLE
Add Vultr for Hosting

### ISSUE THREAD

**Issue by thasmo** [switowski/deploystack#18]
http://vultr.com/

Using them for over a year now and their products are awesome.

**Comment by switowski** [comment]
Thanks for the suggestion - any thoughts on how Vultr compares with other hosting companies (DO, Linode, AWS)?
They seems to offer pretty similar services and pricing as others and I don't want to add another hosting company that has exactly the same features as the other 3. So if there are any features that tell them apart from other companies, I would love to hear about them. Quick googling doesn't return anything special: some people complaining about the slow support: https://www.reddit.com/r/webdev/comments/4am5fh/so_i_compared_digitalocean_and_vultr_over_the, but I guess everyone can have a bad day.

**Comment by thasmo** [comment]
Hey! I'd say one of their most important features is performance. https://www.vultr.com/benchmarks/
There're some comparisons with Digital Ocean online as well which state it has better performance in many aspects.

So, basically they're kind of like a Digital Ocean clone, with more or less the same features, as far as I can tell - but they have a better performance (disk IO, CPU power, etc.)

Feel free to close the issue of you think it's not worthy to put it on the website - I won't be mad. :)

PS: I'm not affiliated with Vultr in any way except being a customer.

**Comment by thasmo** [comment]
Ah, and you can upload custom ISO files - not sure if Digital Ocean allows that by now.

**Comment by switowski** [comment]
Closing, this project will no longer be updated.
