### ISSUE TITLE
Filter by Operating System?

### ISSUE THREAD

**Issue by rosdi** [switowski/deploystack#19]
Unfortunately we could not filter by OS, some of us are developing on .NET and requires Windows hosting. Porting our apps to .NET Core (to be able to host on Linux) isn't trivial.

**Comment by switowski** [comment]
Hi @rosdi, thanks for the suggestion, that's a good point. I will check all the hosting companies and add information if they support Linux or Windows (or both).

**Comment by switowski** [comment]
@rosdi I did some reading and I see that only EC2 from AWS supports Windows VPS machines (DigitalOcean, Linode and LighSails don't have this option). Could you confirm that (if you have experience with those platforms)? Also, do you have any other recommendations for Windows VPS (I see that Azure and Google Cloud support Windows servers).
Also, according to this two links: http://stackoverflow.com/questions/29100993/how-to-deploy-net-application-to-heroku and https://zimmergren.net/building-an-asp-net-5-web-application-net-core-and-host-it-in-the-heroku-cloud/, it's possible to deploy .NET applications on Heroku as well.

**Comment by rosdi** [comment]
Heroku does not support Windows, neither does DigitalOcean, Linode, or LighSails. Only EC2, Azure, and Google support Windows. What you are seeing on Heroku is a new breed of .NET called .NET Core which can run both on Linux and Windows.

But for now most .NET apps requires Windows, it won't work on .NET Core.

To simplify things just add OS filter (Windows / Linux). In the future once .NET Core becomes mainstream, OS type may no longer an issue.

**Comment by switowski** [comment]
Thanks for the clarification! For now, I will add the information about Windows support to EC2 and once I get a separate section for Azure/GCE/AWS (because of their complexity, they need a separate section), I will mention the supported operating systems there.
