### ISSUE TITLE
Serverpilot? 

### ISSUE THREAD

**Issue by partounian** [switowski/deploystack#21]
What are you thoughts on serverpilot.io?

**Comment by switowski** [comment]
Hey,

(I will have to figure out how to get the notifications about new issues in the repo, as currently I'm not getting them :/).
I haven't personally used the serverpilot nor anything else for WordPress, but after a quick research they look pretty interesting and have good reviews. I would deploy Wordpress manually (to have the control over everything, but also to get familiar with what's needed to do this and what's going on on the server), but I see a lot of value for people who just want to have a Wordpress page up and running. Especially, that they have a free plan.
If I create a section dedicated to WordPress, I would definitely add them. Do you have any other recommendations on tools related to WordPress ? Also, have you used the serverpilot? Was it easy to use?

**Comment by partounian** [comment]
I have not used serverpilot, though it seems straightforward. I also like to have full control over my setup, but recently created/migrated a WP site using easyengine and that was great. Performance is insane, though looking over PRs/Issues the security might not be on point for things like SSL settings. But they are doing a complete rewrite of the software so hopefully changes like these are integrated on top of it and it's being built on WP-CLI which is a major plus.

If you would like someone to help you create the WP section, I'd like to be part of it.

**Comment by switowski** [comment]
Nice, they also look interesting. I wasn't aware that there are services that helps you setup WordPress on various infrastructure providers, but it makes perfect sense to do this, based on how many WordPress websites are created every day :)
I'm currently preparing a redesign of DeployStack to make space for more sections, but as soon as it's done, I would be very happy to accept your contributions to the WP section. I will keep you informed!

**Comment by switowski** [comment]
Closing, this project will no longer be updated.
