### ISSUE TITLE
Mention coupon codes for domain names

### ISSUE THREAD

**Issue by KevinColemanInc** [switowski/deploystack#3]
1&1 and Godaddy typically offer promo .com domains for first time users for $1.14 (including the ICANN fee).

**Comment by switowski** [comment]
Thanks for the information, I actually included the promo prices for 1&1 already on the website.
As for Godaddy, there are mixed feelings about this company among developers (one of the examples: https://www.reddit.com/r/web_design/comments/3ht67e/what_is_good_place_to_buy_a_domain_name_ive_heard/), so I decided to keep it off the list.
