### ISSUE TITLE
Firebase?

### ISSUE THREAD

**Issue by mhgbrown** [switowski/deploystack#4]
Great idea consolidating all this information!

[Firebase](https://firebase.google.com/pricing/) might be a nice addition because although it's not as time-tested as, for example, Amazon services, it has robust backing from Google who pushed it pretty hard at the last I/O conference. As an example, Firebase provides a free tier of storage of 5GB with some seemingly generous request limits.

**Comment by switowski** [comment]
Hey, thanks for the feedback and nice words. I know about Firebase and it's a great service, but so far it didn't really fit into any of the sections (as it's not really a one tool, but a set of different tools in one).
But I got a lot of requests about GCE and Azure, so maybe I should think about more advanced tools, where Firebase could also fit. I will keep in on my TODO list :)

**Comment by sampl** [comment]
IMO the _core_ Firebase feature set is basically a PaaS, which would fit well alongside Heroku under "Hosting".

**Comment by sskogen** [comment]
Maybe it is possible to split the hosting section into static and dynamic/server. Firebase Hosting, Github pages, Surge and Netlify offer great static hosting. Heroku is also great for hosting, but primarily for backends, not for static sites - at least not in the free plan, with the lack of a CDN integration and a dyno which needs to sleep regularly.

**Comment by switowski** [comment]
I have added Firebase to the new `Static websites` section. Thanks again for great suggestions!
