### ISSUE TITLE
consider metal servers

### ISSUE THREAD

**Issue by lacion** [switowski/deploystack#5]
there are some really really cheap physical servers out there. even though it can be a bit "harder" to manage than cloud its a good option.

online.net for example

**Comment by switowski** [comment]
Hey, thanks for the feedback. Hosting is the toughest section of the whole website, I got so many suggestions for different companies and I know that many of them are great and maybe even cheaper that Amazon or DigitalOcean. And I know I might be missing some great but small hosting providers, but I want to keep the section small - if I add 10 hosting companies, then this information won't be useful at all (especially to new developers, who are not sure what is important when choosing a hosting) and it will be hard to compare all of them (each company is focusing on slightly different features). I decided to go with the 4 hosting options based on their popularity among developers (basically you can't go wrong with any of them, they will provide a good support if you get stuck, they have tutorials, etc.).
