### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by maxhudson** [switowski/deploystack#8]
Continuous deployment and integration services would be extremely useful to have listed and information about services that integrate well with them (GitHub and Heroku work well with CD, for example).

**Comment by switowski** [comment]
Hi, thanks for the feedback, I have the CI on the roadmap, but didn't really have time to figure it out how to present them nicely (each tool is slightly different). But I will try to cover that section in the future as well :)

**Comment by vircung** [comment]
For CI/CD stack I personally used with main focus of free, GitHub/Slack/Heroku integrations:
- [Travis CI](https://travis-ci.org)
- [Circle CI](https://circleci.com)
- [Semaphore](https://semaphoreci.com)
- [Codeship](https://codeship.com)

**Comment by maxhudson** [comment]
+1 for codeship. The 100 free builds per month on a high quality service is unique.

**Comment by switowski** [comment]
Done, there is a new section called `Continuous Integration` with CircleCI, Codeship and Travis CI as hosted services and Jenkins + GoCD as self-hosted, open source software.
